//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login_Register.Model.DBContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KajalPatel_01_07_2023Entities1 : DbContext
    {
        public KajalPatel_01_07_2023Entities1()
            : base("name=KajalPatel_01_07_2023Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Registration> Registrations { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<Image> Images { get; set; }
        public virtual DbSet<Hobby> Hobbies { get; set; }
        public virtual DbSet<UserRecord> UserRecords { get; set; }
        public virtual DbSet<UserRecord12> UserRecord12 { get; set; }
    }
}
