//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login_Register.Model.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRecord12
    {
        public int RecordId { get; set; }
        public string FullName { get; set; }
        public string Hobbies { get; set; }
    }
}
